### ISSUE TITLE
Feature request: Support for vertical swing options

### ISSUE THREAD

**Issue by slawnz** [nitaybz/homebridge-sensibo-ac#104]
Is it feasible to add support for vertical swing options? Whenever I turn on my AC via HomeKit using the Sensibo homebridge plugin, the vertical swing is set to 'Stopped (auto)' whereas I prefer to have it set to 'Fixed top'. Is there any possibility of exposing options for this via Homekit (maybe as a slider?)

**Comment by benwebbbenwebb** [comment]
Hi @slawnz 

Unfortunately Apple doesn’t expose characteristics (attributes) for this :(
