### ISSUE TITLE
Feature Request: Mitsubishi split QUIET fan speed setting remembered.

### ISSUE THREAD

**Issue by PoppyS33d** [nitaybz/homebridge-sensibo-ac#105]
Firstly, thank you very much for this app!

The issue I have with the Sensibo Sky + all my Mitsubishi split units is that the fan speed in the Homebridge plugin doesn't seem to work properly with the "Quiet" fan speed. What happens is if I leave the unit in Quiet fan mode and turn it off using the Sensibo app (or plugin), when I next use the Homebridge plugin to turn on the AC unit, it defaults back to the "Low" fan speed, which is higher than Quiet, and a bit noisy for me when sleeping. I can then go into the settings of the Homebridge plugin and slide the slider a little more to the left to lower it to "Quiet". But I have to do this every time I turn the unit on from Homebridge. Can something be done to have the Homebridge plugin remember the fan speed setting?

Thank you.

**Comment by benwebbbenwebb** [comment]
How odd @PoppyS33d 
I wonder if there is a rounding error in the conversion from percentage (as required by Home App) to fan level.

When you adjust the percentage is it only 1 or 2 percentage to get it back to the level you want?

Do you happen to be using the latest alpha patch of this plugin or are you using the release version?

Any chance you have debug turned on and have some logs available?

**Comment by PoppyS33d** [comment]
Hi, and thanks for the reply. The slider bar doesn’t look any different when I reopen HomeKit to see, so I’m guessing it’s as you say - a rounding error. I don’t have logging enabled and I’m just running the latest official version. Is there a different version I should run that addresses this? 

Thank you.

**Comment by benwebbbenwebb** [comment]
Hi @PoppyS33d 
I think I've tracked it down (and will put a change in the next version)... to help me confirm can you please share the number of fan levels that your AC unit has?

Ideally please share the names from within the Sensibo app...
Mine for example has:
- Quiet
- Low
- Medium
- High
- Auto
- Strong

But I know some others have things like Medium Low as well

Thanks

**Comment by PoppyS33d** [comment]
> Hi @PoppyS33d I think I've tracked it down (and will put a change in the next version)... to help me confirm can you please share the number of fan levels that your AC unit has?
> 
> Ideally please share the names from within the Sensibo app... Mine for example has:
> 
> * Quiet
> * Low
> * Medium
> * High
> * Auto
> * Strong
> 
> But I know some others have things like Medium Low as well
> 
> Thanks

Thanks for the reply! Yes, the officially named settings available are: Auto, Quiet, Low, Medium, High, Super High.  

Page 8 here:

https://www.mitsubishitechinfo.ca/sites/default/files/IB_MS%28Y%29%28Z%29-GL06_15NA_DG79A01LH01_0.pdf

Thanks!

**Comment by benwebbbenwebb** [comment]
Thanks @PoppyS33d 

Interesting, the issue I found I didn’t think would apply when there is 5 fan levels plus auto… hopefully it does!

Will let you know once the new version is available to test.

**Comment by PoppyS33d** [comment]
> Thanks @PoppyS33d
> 
> Interesting, the issue I found I didn’t think would apply when there is 5 fan levels plus auto… hopefully it does!
> 
> Will let you know once the new version is available to test.

I see. I'll keep my fingers crossed, and test it immediately! Thank you for all your help.

**Comment by benwebbbenwebb** [comment]
Hi @PoppyS33d 

The new alpha is available, please give it a go and let me know how you get on.

Thanks

**Comment by PoppyS33d** [comment]
> Hi @PoppyS33d
> 
> The new alpha is available, please give it a go and let me know how you get on.
> 
> Thanks

Superb! That absolutely works. Now when I use HomeBridge plugin to turn the AC back on, it stays on "Quiet" just like I prefer! Last thing - is there a way for you to add just "Fan" to the list of modes? Currently I only have Heat, Cool, or Auto, but this Mitsubishi also features a fan-only mode.

Thank you again for the support!

**Comment by benwebbbenwebb** [comment]
Great news, thanks for the feedback @PoppyS33d 

As for the Fan mode question... do you have a Fan mode option when you open the Sensibo app? If so, then there should be a Fan accessory showing in the Apple Home app. This extension relies on what Sensibo report your unit supports.

Note: due to Apple limitations, Fan does unfortunately show as a separate accessory (device) in the Home app, and not in the AC unit next to Heat/Cool options :(

Reason a Fan accessory may not be showing:
* it's been disabled in Homebridge (check your settings.json in Homebridge)
* it's been hidden in the Home app (check your Home app settings)
* if it doesn't show in Sensibo either, contact Sensibo support and ask them for an alternate remote code for your unit
