### ISSUE TITLE
This plugin generated a warning from the characteristic 'Rotation Speed': characteristic value expected valid finite number and received "undefined" (undefined)

### ISSUE THREAD

**Issue by mao832** [nitaybz/homebridge-sensibo-ac#109]
Hi, getting continuos warnings in the logs like the following one (every 5 seconds):

[05/09/2023, 12:49:29] [homebridge-sensibo-ac] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.

Plugin is updated to v.2.3.4-release and working without issues, it is just annoying to see logs like that.

Using 2 Sensibo Sky (SEN-SKY-01-WH).

Homebridge version 1.6.1, NodeJS v18.17.1 running on Raspberry Pi 4.

![image](https://github.com/nitaybz/homebridge-sensibo-ac/assets/121161067/995566fe-3166-4c45-85a8-b17f1647cda6)

**Comment by i-am-pierre** [comment]
I'm having the same behavior.
Config:
1 Sensibo Air, 3 Sensibo Sky
HomeBridge 1.6.1, Synology app, separate child bridge with plug-in 2.3.4. NodeJS 18.5

**Comment by mao832** [comment]
Is it possible to add an option in the configuration to remove entirely the logs maybe?

**Comment by benwebbbenwebb** [comment]
#63 sounds like same root cause

**Comment by benwebbbenwebb** [comment]
Hi @mao832 and @i-am-pierre 

Are you able to try the current alpha out to see if it fixes your issue?

See https://github.com/nitaybz/homebridge-sensibo-ac/issues/63#issuecomment-1494032187 for instructions.

Please also be aware you may need to restart your Homebridge entirely after the install to make sure the changes take effect.

**Comment by mao832** [comment]
> Hi @mao832 and @i-am-pierre
> 
> Are you able to try the current alpha out to see if it fixes your issue?
> 
> See [#63 (comment)](https://github.com/nitaybz/homebridge-sensibo-ac/issues/63#issuecomment-1494032187) for instructions.
> 
> Please also be aware you may need to restart your Homebridge entirely after the install to make sure the changes take effect.

Hi, since some days I don't see the warning anymore, everything is the same except NodeJS which now is version 20.9.0, don't know if it might have been the root cause of the issue maybe?

I would close this issue for now since at least for me it's solved, thanks anyway for the reply and the support!
