### ISSUE TITLE
'Dry Mode' can not be turned off 

### ISSUE THREAD

**Issue by TzachiGuetta** [nitaybz/homebridge-sensibo-ac#11]
@nitaybz, since v1.1.4 the Dry mode is always presented in HomrKit - although its turn off in the configuration. 
environment : hoobs v3.2.6 (latest)

**Comment by sleepyarmistice** [comment]
I'm experiencing the same issue.

**Comment by nitaybz** [comment]
the issue should be fixed now... please update to the latest 1.1.8 and let me know

**Comment by TzachiGuetta** [comment]
@nitaybz, thanks !
I still see “latest” for hoobs = 1.1.7

**Comment by TzachiGuetta** [comment]
issue still reproduced

**Comment by nitaybz** [comment]
correct... sorry for the ping-pong... i'm not in a position to test.
but it should be solved in the recent 1.1.10

**Comment by TzachiGuetta** [comment]
@nitaybz, Works!
