### ISSUE TITLE
Temp selection increments

### ISSUE THREAD

**Issue by ds2288** [nitaybz/homebridge-sensibo-ac#116]
Any chance the temperature increments can be 0.5 degrees Celsius instead of 1. The air con remote and Sensibo HomeKit integration does it in 0.5 degree increments.

**Comment by benwebbbenwebb** [comment]
Hello @ds2288 

Good question! Unfortunately no...

The Sensibo API specs, [see here](https://sensibo.github.io/#post-/pods/-device_id-/acStates), state that the target temperature needs to be an integer! Not sure why using HomeKit directly allows .5 degree increments... I also checked in the Sensibo app and (for my devices at least - but I guess it could be make and model specific) it is integer only.
