### ISSUE TITLE
Still getting “Unhandled Promise Rejection Warning”

### ISSUE THREAD

**Issue by schwa23** [nitaybz/homebridge-sensibo-ac#13]
I saw a previous issue was fixed, but I’m still getting an Unhandled Promise Rejection Warning.

[6/7/2020, 1:33:32 AM] Initializing platform accessory 'Office AC'...
HAP Warning: Characteristic 00000010-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000BC-0000-1000-8000-0026BB765291. Adding anyway.
(node:2100) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'fanLevels' of undefined
    at acAccessory.getServices (/homebridge/node_modules/homebridge-sensibo-ac/lib/accessories.js:196:65)
    at Server.createHAPAccessory (/usr/local/lib/node_modules/homebridge/src/server.ts:441:41)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:426:34
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:416:21
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at SensiboACPlatform.accessories (/homebridge/node_modules/homebridge-sensibo-ac/index.js:234:3)
(node:2100) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2100) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by schwa23** [comment]
FWIW, I’m running the latest version of Homebridge on a raspberry pi via the official docker image.

**Comment by nitaybz** [comment]
the issue should be fixed now... please update to the latest 1.1.8 and let me know

**Comment by schwa23** [comment]
yes, it works! Thanks!
