### ISSUE TITLE
An unknown accessory appears

### ISSUE THREAD

**Issue by bakkalerdal** [nitaybz/homebridge-sensibo-ac#145]
Hello,

I have been using the plugin for a long time. After the last update, a problem occurred. The options “Disable Dry Acc,” “Disable Fan Acc,” “Disable Light Switch,” and “Disable Horizontal Swing” are selected to ensure that only one accessory appears in HomeKit. This way, only the air conditioner controller shows up in HomeKit, allowing me to turn the air conditioner on and off with just a tap, without needing to group or ungroup.

However, the issue starts here. Sometimes (not more than once a week), an additional accessory named “Air Conditioner” (the name I’ve given to my AC) appears on its own and stays in the “Not Responding” mode. Because of this, I can’t turn the air conditioner on and off with a single tap. I have to go into the accessory, select the air conditioner, and operate it from there. If I ungroup and separate it, I end up with an accessory that doesn’t work and says “Not Responding.”

To fix this, I restart Homebridge, and the problem is resolved, and this unidentified accessory disappears.

I am reporting the issue to you and kindly request a solution.

Thank you.
<img width="392" alt="Ekran Resmi 2024-07-28 10 28 32" src="https://github.com/user-attachments/assets/89edc897-c02d-4903-af0b-25839ee57c68">

**Comment by benwebbbenwebb** [comment]
Hi @bakkalerdal 

That sounds quite annoying and strange!

If it's not too much trouble would you mind visiting `Settings` in your Homebridge, scrolling down to `Remove Single Cached Accessory` and then deleting any AC units shown from homebridge-sensibo-ac?

**_Note_** this unfortunately will also remove it from any automations or scenes.

Once it's deleted please restart Homebridge again and then hopefully only a single copy will be re-added.

Please let me know how you go.

**Comment by benwebbbenwebb** [comment]
Hi @bakkalerdal 

Any luck?

**Comment by bakkalerdal** [comment]
> Hi @bakkalerdal
> 
> Any luck?

I was going to write about the updates today as well. Unfortunately, the issue hasn't been resolved. I completely uninstalled and reinstalled the plugin, but the same problem persists.

This time, while reinstalling the plugin, I also enabled the option to display the Dehumidify mode as a separate accessory. Two more accessories named 'AC' started to appear randomly on their own. Of course, they show up as 'Not Responding'. Before doing this, there was only 1 non-responsive accessory.

I'm trying to temporarily fix the issue by choosing to display them as separate tiles and hiding these non-responsive accessories.

Thank you.

**Comment by benwebbbenwebb** [comment]
> Hi @bakkalerdal
> 
> That sounds quite annoying and strange!
> 
> If it's not too much trouble would you mind visiting `Settings` in your Homebridge, scrolling down to `Remove Single Cached Accessory` and then deleting any AC units shown from homebridge-sensibo-ac?
> 
> **_Note_** this unfortunately will also remove it from any automations or scenes.
> 
> Once it's deleted please restart Homebridge again and then hopefully only a single copy will be re-added.
> 
> Please let me know how you go.

Hi @bakkalerdal 

Have you tried the steps suggested here to delete cached accessories? This is separate and different to removing the plugin.

**Comment by benwebbbenwebb** [comment]
Please also check, within your Home app under Home Settings, if you have multiple Bridges appearing.

**Comment by bakkalerdal** [comment]
> > Hi @bakkalerdal
> > That sounds quite annoying and strange!
> > If it's not too much trouble would you mind visiting `Settings` in your Homebridge, scrolling down to `Remove Single Cached Accessory` and then deleting any AC units shown from homebridge-sensibo-ac?
> > **_Note_** this unfortunately will also remove it from any automations or scenes.
> > Once it's deleted please restart Homebridge again and then hopefully only a single copy will be re-added.
> > Please let me know how you go.
> 
> Hi @bakkalerdal
> 
> Have you tried the steps suggested here to delete cached accessories? This is separate and different to removing the plugin.

I forgot to try it. I’ll test it and share the results.

**Comment by bakkalerdal** [comment]
When I cleared the cache, it was fixed. Thank you.
