### ISSUE TITLE
Humidity sensor unresponsive 

### ISSUE THREAD

**Issue by strangeblue** [nitaybz/homebridge-sensibo-ac#146]
Since the update all of my humidity sensors show as unresponsive in the home app

**Comment by benwebbbenwebb** [comment]
Hi @strangeblue 

Sorry to hear this! What troubleshooting have you done so far?

If not already done, please restart Homebridge completely (or the entire computer running Homebridge). If that doesn't work what, if any, is reported in the logs? Please also clarify what you're doing in the Home app that shows that they are unresponsive.

It would also be really helpful to turn on debug logging ([see README for more info](https://github.com/nitaybz/homebridge-sensibo-ac/blob/master/README.md#troubleshooting-and-debug)) and share any relevant output.

Also, do you have any of these set in your config?
- `disableHumidity`
- `externalHumiditySensor`

**Comment by benwebbbenwebb** [comment]
Hi @strangeblue 

Any luck?

**Comment by strangeblue** [comment]
Hi there.Sorry I’ve been busy with work and haven’t had time to look at any of this. I’ve removed the humidity sensors from the Sensibo config as a solution. I’ll try to get some time to troubleshoot but feel free to close off the ticket and I’ll get back to you if I need. Sorry. SteveOn 16 Aug 2024, at 20:08, Ben ***@***.***> wrote:﻿
Hi @strangeblue
Any luck?
