### ISSUE TITLE
Dry Mode Issues

### ISSUE THREAD

**Issue by dampney** [nitaybz/homebridge-sensibo-ac#15]
Hey,

I’ve got my Mitsubishi AC setup in my Homekit. I’ve got my AC ungrouped.  I was previously using a different plugin but switched to this “Certified” hoping better support.

My issue:

Whenever I open my main AC tile in Homekit, it turns off my Dry tile and switches to Cool Mode. If my AC is off, opening my AC tile it doesn’t automatically turn on which is expected. But with my AC in Dry Mode, opening the AC accessory it automatically turns off Dry, and turns on Cool.

I’ve confirmed the Sensibo app follows all these changes and keeps a constant update.

**Comment by nitaybz** [comment]
I'll check and get back to you... thanks for updating

**Comment by nitaybz** [comment]
Please try version 1.1.15

**Comment by nitaybz** [comment]
@dampney any news?

**Comment by galrozov** [comment]
I had this issue before but since the latest versions it doesn’t happen anymore.

**Comment by nitaybz** [comment]
Thanks for the update..
Closing

**Comment by dampney** [comment]
> @dampney any news?

Yes, it’s fixed and working well. I can now have all my AC controls in one HomeKit tile - thank you
