### ISSUE TITLE
Request: Separate humidity sensor

### ISSUE THREAD

**Issue by bwoodruff** [nitaybz/homebridge-sensibo-ac#16]
As per subject line: would like to have a separate tile in Home app for humidity sensor. <s>At present it doesn't appear possible to view the humidity reading from the Sensibo in the Home app.</s> I take part of that back: it is possible to see the humidity, but you have to dig for it, particularly if you have the accessories grouped.

**Comment by nitaybz** [comment]
the question is, why would you want the extra accessory, would it be just for monitoring?
because automations can work based on that part of the accessory and not necessarily need it as an extra accessory

**Comment by nitaybz** [comment]
done :)

it's available in version 1.1.13

**Comment by bwoodruff** [comment]
Yes exactly, for monitoring. Thank you!
