### ISSUE TITLE
Temperature Reading

### ISSUE THREAD

**Issue by richsc** [nitaybz/homebridge-sensibo-ac#17]
The temperature reading (Celsius) in HomeKit is currently rounded to 0.5% 
Can it be changed to display to one decimal place the exact temperature or is this a limitation within the ios Home app?

**Comment by nitaybz** [comment]
are you talking about the current room temperature or the target temp?
Target temp - should be in round steps without decimal point
current room temp - HomeKit is getting it rounded to 0.1 but it round it to 0.5 automatically... you can verify it by using another app like Eve to view that.

**Comment by richsc** [comment]
Hi, thanks for your reply.

I was referring to the room temperature.  So you are saying that the Apple
Home App is rounding it to 0.5 and this cannot be changed unless Apple
decide to do so.

Regards,
Richard

**Comment by nitaybz** [comment]
indeed... Home app limitation... adding those images to show you how it's different from Eve.

<img width="414" alt="Screenshot 2020-06-23 at 10 37 48" src="https://user-images.githubusercontent.com/16838394/85375942-b86deb80-b53f-11ea-89de-91d94cef6f8d.png">
<img width="414" alt="Screenshot 2020-06-23 at 10 09 05" src="https://user-images.githubusercontent.com/16838394/85375943-b86deb80-b53f-11ea-9787-8c9bf20beaa9.png">


Closing...
