### ISSUE TITLE
can't control AC temperature with Siri commands 

### ISSUE THREAD

**Issue by TzachiGuetta** [nitaybz/homebridge-sensibo-ac#19]
@nitaybz,
environment : hoobs v3.2.6 (latest)

**Comment by nitaybz** [comment]
tell Siri to "Set Cooling Threshold to x" or "Set Heating Threshold to x"

**Comment by TzachiGuetta** [comment]
![WhatsApp Image 2020-06-23 at 12 33 54](https://user-images.githubusercontent.com/7381350/85387890-11448080-b54e-11ea-9ffc-ce789b59e0ce.jpeg)

**Comment by nitaybz** [comment]
try Set Cooling Threshold Temperature to x

**Comment by TzachiGuetta** [comment]
Works! previously it works by just saying "set temperature 24 degrees"
