### ISSUE TITLE
config issue

### ISSUE THREAD

**Issue by sidhuamansingh** [nitaybz/homebridge-sensibo-ac#2]
![Screen Shot 2020-05-05 at 1 42 55 PM](https://user-images.githubusercontent.com/64826869/81037726-5ba66b00-8ed6-11ea-9552-23d2ddf6d8c3.png)
Hi im a novice and I'm having issue as per below image..I have already gotten my KEY and ill just paste it there it still shows that error. what am I doing wrong?
![Screen Shot 2020-05-05 at 1 42 12 PM](https://user-images.githubusercontent.com/64826869/81037694-429dba00-8ed6-11ea-8fac-4a172d572438.png)

**Comment by nitaybz** [comment]
yeah you did it wrong... please paste your entire config as text and i'll try to re-arrange it for you

**Comment by nitaybz** [comment]
hope it resolved, but definitely not a plugin error, so closing...
