### ISSUE TITLE
Can’t control fan speed via Home app

### ISSUE THREAD

**Issue by galrozov** [nitaybz/homebridge-sensibo-ac#22]
We don’t use FAN mode in our home, only Cool/Heat/Dry, so I disabled it in the configuration.

But now when we set the AC to cool we don’t have a slider for the fan speed shown in the HOME app, see attached screenshot.
(AC is Tadiran)
![1FA1D1AC-760A-4010-B433-CBA2D7C4C74A](https://user-images.githubusercontent.com/2068310/86257758-a7b61900-bbc2-11ea-97bc-5ed363a23e53.png)

**Comment by galrozov** [comment]
![CDBA5CB2-B812-4D0C-9085-36EBCADDDAE8](https://user-images.githubusercontent.com/2068310/86259784-1c8a5280-bbc5-11ea-94c0-2ae986be4691.png)

**Comment by nitaybz** [comment]
The fan speed is not controlled by the fan accessory or anything related... you should access the accessory settings and change the fan speed there:
![image](https://user-images.githubusercontent.com/16838394/86275085-654d0600-bbdb-11ea-96b2-140b86543783.png)

**Comment by nitaybz** [comment]
It's written everywhere in the README

**Comment by galrozov** [comment]
Screenshot could be best as I didn’t notice.

‫ב-1 ביולי 2020, בשעה 21:14, ‏‏Nitay Ben-Zvi ‏<notifications@github.com> כתב/ה:‬

﻿

It's written everywhere in the README

**Comment by Brkie** [comment]
I have no fan speed in my AC settings. I have tryied with fan dissabled and enabled.. ideas?
