### ISSUE TITLE
Unable to uninstall or update homebridge-sensibo-ac 1.0.6 on Hoobs 3.2.6

### ISSUE THREAD

**Issue by dominvepf** [nitaybz/homebridge-sensibo-ac#23]
Hi, my Hoobs service keeps on shutting down, it usually happens right after I use the sending UI in HomeKit.
I noticed there is an update available but it fails silently to update when I click the update button.
I tried to completely remove the plugin but that also fails silently. Every time I go to the plugins list, homebridge-sensibo-ac 1.0.6 is still there.

I even tried to manually uninstall from terminal using
sudo npm uninstall homebridge-sensibo-ac
but I received:
npm ERR! code EEXIST
npm ERR! path /home/hoobs/.hoobs/node_modules/homebridge-sensibo-ac/node_modules/.bin/mkdirp
npm ERR! Refusing to delete /home/hoobs/.hoobs/node_modules/homebridge-sensibo-ac/node_modules/.bin/mkdirp: is outside /home/hoobs/.hoobs/node_modules/homebridge-sensibo-ac/node_modules/mkdirp and not a link
npm ERR! File exists: /home/hoobs/.hoobs/node_modules/homebridge-sensibo-ac/node_modules/.bin/mkdirp
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-14T02_26_36_278Z-debug.log

So I tried with the --force option and still got an error:
npm WARN using --force I sure hope you know what you are doing.
npm ERR! code EEXIST
npm ERR! path /home/hoobs/.hoobs/node_modules/homebridge-sensibo-ac/node_modules/.bin/mkdirp
npm ERR! Refusing to delete /home/hoobs/.hoobs/node_modules/homebridge-sensibo-ac/node_modules/.bin/mkdirp: is outside /home/hoobs/.hoobs/node_modules/homebridge-sensibo-ac/node_modules/mkdirp and not a link
npm ERR! File exists: /home/hoobs/.hoobs/node_modules/homebridge-sensibo-ac/node_modules/.bin/mkdirp
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-14T02_28_24_139Z-debug.log

I am at a loss as to how to resolve this. For now I will just avoid using sensibo in HomeKit and use it directly in the sensibo app, but your help would be appreciated.

Thanks

**Comment by BobbySlope** [comment]
tr this command toi remove the plugin:

sudo rm -Rf /home/hoobs/.hoobs/node_modules/homebridge-sensibo-ac

theres no terminal output after this command, check the plugins section it should be removed
then reinstall the plugin with the new version

**Comment by dominvepf** [comment]
Wonderful, thanks for the help, I was able to remove the old version and now the new version is installed and working.

Have a nice day!
_________________________________________________________________
Prof. Dr. Dominic Villeneuve, Ph.D.
dominicvilleneuve@live.ca <mailto://dominicvilleneuve@live.ca> | Web: http://DominicVilleneuve.ca <http://dominicvilleneuve.ca/>
