### ISSUE TITLE
Add Horizontal swing support

### ISSUE THREAD

**Issue by galrozov** [nitaybz/homebridge-sensibo-ac#24]
One of my tadiran AC units has also horizontal swing motor and not just vertical swing like other ACs. 
From the Sensibo App I can control both the vertical and the horizontal swing movements, can you add this option to Homekit?

**Comment by nitaybz** [comment]
I don't have that feature... will try to get it from Sensibo.

Anyway, I can add it as an extra switch and not as a part of the accessory because it is not supported by HomeKit.

**Comment by nitaybz** [comment]
Available in the latest version 2.0.0
