### ISSUE TITLE
install fail on Hoobs

### ISSUE THREAD

**Issue by bbaik** [nitaybz/homebridge-sensibo-ac#26]
hi,

Im trying to install but it keeps giving me a failed reply.

Log:

8/3/2020, 7:16:43 PM npm
8/3/2020, 7:16:43 PM  ERR!
8/3/2020, 7:16:43 PM  Unexpected end of JSON input while parsing near '...typescript3":"npm:typ'
8/3/2020, 7:16:43 PM 
8/3/2020, 7:16:43 PM npm ERR! A complete log of this run can be found in:
npm ERR!
8/3/2020, 7:16:43 PM      /home/hoobs/.npm/_logs/2020-08-03T23_16_43_407Z-debug.log

can u lend a hand?

thanks

**Comment by BobbySlope** [comment]
Please provide more information, logs, config with personal data removed. Which plugin?
