### ISSUE TITLE
Fan Mode, without the Fan accessory ?

### ISSUE THREAD

**Issue by Pblondin123** [nitaybz/homebridge-sensibo-ac#30]
Hi, is it possible to have a Fan mode in the accessory controls, without having to enable the Fan accessory ? tya

**Comment by nitaybz** [comment]
Correct me if I'm wrong but it seems like you are asking to add the Fan mode to the ac accessory and not to add a new separate accessory... if this is your request I have to say it's not possible.... HomeKit limitation.
That is why I created it this way... really wish fan and dry will be part of the AC accessory

**Comment by Pblondin123** [comment]
Correct, Fan mode to the ac accessory.   Too bad and thanks!
