### ISSUE TITLE
Sync AC is in seperate control from 2.0

### ISSUE THREAD

**Issue by benji1703** [nitaybz/homebridge-sensibo-ac#32]
Hi,

Since 2.0 - the 'Sync AC' switch is not showing to me under the Thermostat control, but as an independent switch.
I could not find any possibility to set this in the UI of Home, is this something that changed from the previous version? Is this possible to throw it back in the Thermostat control?

Thanks 🥇

**Comment by nitaybz** [comment]
Hey, I've separated it due to requests from users... If I'll see more requests to put it back I'll also include an option for it...
I'm also curious to see how things will look on the new iOS 14.

at the moment I'll leave it as it is for a while.
sorry...

**Comment by benji1703** [comment]
Thank you very much for this plugin.
I will probably later on today / this week fork out and add this option as a configuration.

**Comment by nitaybz** [comment]
@benji1703 haven't tested it yet cause I don't have the chance at the moment, so please tell me if it acts as expected

**Comment by benji1703** [comment]
I forked and add the option - Working great, as well as in iOS14.
Added this as an additional option so one can add both sync button and the integrated one in the AC control.
And again - thank you very much for your wonderful project

**Comment by nitaybz** [comment]
Hey... yesterday night I uploaded a version with the feature you wanted... thought you noticed it :)

**Comment by nitaybz** [comment]
Add "syncButtonInAccessory": false to your config

**Comment by benji1703** [comment]
Thank you very much for this, this is wonderful (and working! 💯 )
