### ISSUE TITLE
Freeze in iOS 14.1 sence

### ISSUE THREAD

**Issue by wallacepost** [nitaybz/homebridge-sensibo-ac#35]
Hi , when I adding / editing the Sensibo to a sence in iOS 14.1 & It freeze . I have test for others sence without the sensibo, works fine.

**Comment by nitaybz** [comment]
14.1? You mean beta version or 14.0.1 Public version.

Because I'm using iOS 14.0.1 and it works well.
Can you give your details about your issue?
Have you tried to restart homebridge?

**Comment by nitaybz** [comment]
still occures?
