### ISSUE TITLE
Temperatur limits

### ISSUE THREAD

**Issue by erling-henningsen** [nitaybz/homebridge-sensibo-ac#36]
Hi
My Panasonic AC  can be set to 8, 10 and 16-30 C.
When I use the Sensibo app the temp selections is limit to these temperaturs.
When I use the plugin the temperatur can be set to eg. 14C.  The temperatur settings is not changed in the AC but the illegale temperatur is shown in Homekit.
Regards
Erling

**Comment by nitaybz** [comment]
unfortunately... this is not something I change...
you have to admit it is super weird behaviour :)
HomeKit can't allow specific temperatures, only min & max.

I would ask Sensibo to remove 8 & 10 from your setup so it will show normally 16-30.
hope it helps

**Comment by erling-henningsen** [comment]
8 and 10 C is used for frost protection during winter time so they are nice to have :)
When the plugin thy to set a illegal values in Sensibo nothing is actually changed in the AC and in Sensibo. Will it be possible for you to refresh the Homekit value again with the actual/old value from Sensibo.

**Comment by nitaybz** [comment]
it should automatically refresh after the next round of status polling

**Comment by erling-henningsen** [comment]
What is the polling freq. ?
When I set a illegal temperatur it never change back again not even if I change the temperatur in the Sensibo app. It only change/refresh if I set a legal temperatur in Homekit again.

**Comment by nitaybz** [comment]
it should refresh every 90 seconds, if it's not changing I would like to see the logs.... please do the following:
1. Set "legal" temperature in HomeKit.
2. Add "debug logs" to your config via plugin settings.
3. Restart homebridge.
4. after HomeBridge restarted completely, set to illegal temperature, close the Home app, wait 10 seconds, open the app again.
5. send me logs
6. wait another 90 seconds when Home app is closed, then, open again and see if state is changed.
7. send logs again

can you do that?

**Comment by erling-henningsen** [comment]
I will do it later and return :-)

**Comment by nitaybz** [comment]
Thanks

**Comment by erling-henningsen** [comment]
Include please find a log
I went trough the following steps:

1. Set "legal" temperature in HomeKit.
2. Add "debug logs" to my plugin settings.
3. Restart homebridge.
4. Set illegal temperature 14C, closed the Home app, wait 10 seconds, opened the app again.
5. Wait 2 min. closed and opened Home app.
6. Wait for several minutes 
7. Set legal temperatur  10 C
8. Closed and opened Home app

It looks like you dont make the correct GET request to Sensibo API when the temperatur is illegale.

[homebridge1.log.txt](https://github.com/nitaybz/homebridge-sensibo-ac/files/5397524/homebridge1.log.txt)

**Comment by nitaybz** [comment]
Thanks to your help I found a bug... it should be solved in 2.0.12
also, now when you set an "illegal" command... it should revert quickly in HomeKit to the current state in Sensibo

**Comment by erling-henningsen** [comment]
Thanks, the temperatur is now refreshed to the last legal value if I enter a illegale temperatur.

**Comment by nitaybz** [comment]
amazing! glad it work :)
