### ISSUE TITLE
Request: Seperate Temperature Sensor

### ISSUE THREAD

**Issue by darwiniandude** [nitaybz/homebridge-sensibo-ac#39]
EDIT: Essentially, current room temp doesn't appear to be exposed to HomeKit as a sensor that can be automated, for some reason.

I'd like to make something else happen based on the temperature reported by Sensibo. However, I've recently set up Homebridge and everything is working great, but at least under current iOS 14.2, only my Dyson air purifier shows as a sensor I can create and automation with.

I saw the previous request #39 for a separate humidity sensor, you said to the person:
"the question is, why would you want the extra accessory, would it be just for monitoring?
because automations can work based on that part of the accessory and not necessarily need it as an extra accessory"

So based on that, I'd assume I should be able to create an automation based on temp from sensibo now? I can see the temp, in the home icon, but it doesn't show as something I can create an automation from. Odd.

**Comment by nitaybz** [comment]
To create temperature based automation you need any other 3rd party app. I would recommend Eve.
Home app is not yet able to automate biased on humidity or temperature
