### ISSUE TITLE
Don't working "Device locations to include"

### ISSUE THREAD

**Issue by Valdemar1111** [nitaybz/homebridge-sensibo-ac#41]
In app sensibo I have 2 locations. in first 3 devises and in the second 5 devises. in the setting in homebridge-sensibo-ac I fill  second group, witch has name " donskoy", and  nothing happens. everything disappeared.

**Comment by nitaybz** [comment]
how did you try?
did you insert location ID? can you share the config?

**Comment by Valdemar1111** [comment]
when when it is filled, it look like this:
            "username": "*********",
            "password": "********",
            "disableFan": false,
            "disableDry": true,
            "enableSyncButton": false,
            "syncButtonInAccessory": false,
            "enableOccupancySensor": false,
            "enableClimateReactSwitch": false,
            "enableHistoryStorage": false,
            "disableHorizontalSwing": false,
            "externalHumiditySensor": true,
            "locationsToInclude": [
                "Донской"
            ],
            "debug": false,
            "platform": "SensiboAC"
But  devises not show...

**Comment by Valdemar1111** [comment]
may be I misunderstanding the location id

**Comment by nitaybz** [comment]
the plugin only accepts ID as the location to filter... but I just pushed another version (v2.0.22) that support sending location name as well... so please try again...
by the way... you don't have to use this feature and can leave it empty to include all location devcies

**Comment by Valdemar1111** [comment]
well, if I leave the column empty, how can I remove unnecessary devices

**Comment by nitaybz** [comment]
what are unnecessary devices? devices on other homes?
The idea behind the "include location" feature is to remove devices on other houses under your account

**Comment by Valdemar1111** [comment]
Yes, it is  devices on other homes.

**Comment by nitaybz** [comment]
So please update the plugin to version 2.0.22 and try again with the location name

**Comment by Valdemar1111** [comment]
location name  is it address or home name?
Thank you!

**Comment by nitaybz** [comment]
home name in Sensibo app

**Comment by Valdemar1111** [comment]
Now everything work, thank you!
