### ISSUE TITLE
[Feature request] Light switch

### ISSUE THREAD

**Issue by esteban-mallen** [nitaybz/homebridge-sensibo-ac#45]
First of all, I love this plugin! Really stable and full featured!

Now, would it be possible to add the A/C light switch as an accessory switch or something in the like? Here's a screenshot of the Sensibo app button I'm referring to.

![IMG_19A428C74952-1](https://user-images.githubusercontent.com/5589148/103925186-e5f23f00-50f5-11eb-9f1e-1e31c033a2d6.jpeg)

Thanks!

**Comment by nitaybz** [comment]
will do

**Comment by nitaybz** [comment]
I don't have this feature but I implemented it in the plugin... please let me know if it works.

**Comment by nitaybz** [comment]
tested and working in the latest version
