### ISSUE TITLE
Only shows Celsius in Homekit

### ISSUE THREAD

**Issue by sieteunoseis** [nitaybz/homebridge-sensibo-ac#5]
Sensibo is set to F but HomeKit shows in Celsius

**Comment by nstefanelli** [comment]
Also seeing this issue. Confirmed HomeKit is set, Sensibo set in the app for me to F as well.

**Comment by nitaybz** [comment]
Hey Guys... please install the latest version and report back :)
thanks

**Comment by bnaturalpa** [comment]
Looks like that fixed it, thanks

**Comment by nitaybz** [comment]
Please test the latest 1.0.11

**Comment by nitaybz** [comment]
Closing and continuing in #8 which is a duplicate

**Comment by nitaybz** [comment]
the issue should be solved anyway
