### ISSUE TITLE
Warning in the log 

### ISSUE THREAD

**Issue by JacVid** [nitaybz/homebridge-sensibo-ac#50]
Hello,

Are you aware about this warning ?

_[homebridge-sensibo-ac] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 17 exceeded minimum of 18. See https://git.io/JtMGR for more info._

I'm running HomeBridge v1.3.3 & homebridge-sensibo-ac v2.1.2 on a RPi.

Thanks

**Comment by JacVid** [comment]
This warning is more and more increasing the log size. Now this warning appears each minute, and thus slow down my RPi... Help !

**Comment by nitaybz** [comment]
each minute will not slow down your pi but I will take care of it... don't stress :)

**Comment by i-am-pierre** [comment]
Seeing similar issues on mine as well.

"homebridge-sensibo-ac] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info."

The plugin is running a a child bridge on HomeBridge v1.3.3 running on container (Ubuntu Bionic Beaver (18.04.5 LTS)).

Do you need any logs?

**Comment by nitaybz** [comment]
do you guys both use Fahrenheit as temp unit?
also, if you could add debug logs to the plugin settings that would help to set a proper solution

**Comment by JacVid** [comment]
I’m in Celsius.

**Comment by i-am-pierre** [comment]
I'm also using Celsius. I've attached a small output from the debug logs. Let me know if this is enough for you.
[Debug logs.log](https://github.com/nitaybz/homebridge-sensibo-ac/files/6152973/Debug.logs.log)

**Comment by JacVid** [comment]
Hello,

here is my log

[SensiboLog.txt](https://github.com/nitaybz/homebridge-sensibo-ac/files/6154558/SensiboLog.txt)

**Comment by nitaybz** [comment]
Thanks guys... I've learned a lot from your logs... those are situations I haven't seen yet... will be corrected

**Comment by JacVid** [comment]
Hello,
I had to deactivate the plugin, because it was writing a warning log every minute which has damaging my SD Card.
Please correct it :)
Thanks.

**Comment by nitaybz** [comment]
would appreciate if you guys could check v2.1.4.
it should solve all warnings... I'm waiting for your feedback

**Comment by i-am-pierre** [comment]
> would appreciate if you guys could check v2.1.4.
> it should solve all warnings... I'm waiting for your feedback

It seems good to me since 2.1.4 update. I can’t duplicate the behaviour.  Thanks!

**Comment by JacVid** [comment]
Thanks a lot nitaybz, it works perfectly ! You did a great job, I appreciate.
