### ISSUE TITLE
Does this plugin also work with sensibo pure?

### ISSUE THREAD

**Issue by vhm14u2c** [nitaybz/homebridge-sensibo-ac#51]
Description is main question, I bought sensibo pure about a week ago.

**Comment by nitaybz** [comment]
Not at the moment

**Comment by simon-bd** [comment]
Do you have any plans to add it?😁

**Comment by nitaybz** [comment]
In general yes... I just don't have the device yet

**Comment by simon-bd** [comment]
If you need testing I have the device and would be up for testing!

**Comment by simon-bd** [comment]
Any news here? :)

**Comment by nitaybz** [comment]
not yet :)

**Comment by vhm14u2c** [comment]
Just an FYI, sensibo added 'pure' to HomeKit, and works.
Here are setup instructions-

https://support.sensibo.com/l/en/article/v55v2xzpmu-homekit-for-sensibo-pure

This issue can be closed IMO.

**Comment by nitaybz** [comment]
The device now supports "Sensibo Pure"
Checkout version 2.2 release notes: 
https://github.com/nitaybz/homebridge-sensibo-ac/releases/tag/v2.2.0
