### ISSUE TITLE
Issues when account details changed. 

### ISSUE THREAD

**Issue by sidhuamansingh** [nitaybz/homebridge-sensibo-ac#53]
When username/email and password is changed to another account the previous devices still appear on the accessory and the new account devices does not appear. Troubleshooting done includes uninstalling and reinstalling plugin , restarting pi server

**Comment by sidhuamansingh** [comment]
is it possible that the username doesn't accept a @hotmail.com email?

**Comment by nitaybz** [comment]
I fixed it in version 2.2
