### ISSUE TITLE
A way to disable log ?

### ISSUE THREAD

**Issue by JacVid** [nitaybz/homebridge-sensibo-ac#55]
Hello,

is there a way to disable the log ?

Actually, each action via the plugin writes a log of all operations. It could be useful to disable these logs to limit the writing. But of course the warning must still displayed.

Thanks

**Comment by nitaybz** [comment]
The plugin is currently writing only the "set" commands and errors... no status logs... anyway I'll move the "set" commands to the "debug logs" feature and leave only errors in the main log.

**Comment by nitaybz** [comment]
fixed it in version 2.2

**Comment by JacVid** [comment]
Thanks for your work ;)
