### ISSUE TITLE
API usage

### ISSUE THREAD

**Issue by BigJazzz** [nitaybz/homebridge-sensibo-ac#58]
Are there plans to implement API usage to move away from supplying your username and password?

**Comment by nitaybz** [comment]
there is already an api usage... you can use api key instead of username and password

**Comment by nitaybz** [comment]
I've found it easier for users to use username and password... although I can give both options equal attention

**Comment by nitaybz** [comment]
I've added API key instructions in the UI form.
It's available in version 2.2
