### ISSUE TITLE
when AC is in "dry" mode. Homekit icon did not lit up, only showing "lowering to"

### ISSUE THREAD

**Issue by phsung** [nitaybz/homebridge-sensibo-ac#59]
Normally when AC is in "cool" mode the homekit icon will be shown as turned on (lit up), but when switching to dry mode, the icon didn't lit up but only showing the text "lowering to..."

**Comment by nitaybz** [comment]
just scroll down in the accessory and click on "Show as split tiles" this will reveal all accessories

**Comment by phsung** [comment]
Thanks for the reply. Yes I am aware of that, but whenever the AC is not turned off, it should be "on" right? This should include  dry mode, or even fan mode. Thanks

**Comment by nitaybz** [comment]
Dry mode and fan mode are not native in HomeKit, therefore I created separate accessory for each of them, so for example if you switch to dry mode, the ac accessory will turn off and the dehumidifier accessory will be on instead. Same goes for the fan mode, the fan accessory will represent this mode

**Comment by nitaybz** [comment]
So not an issue here... closing
