### ISSUE TITLE
Current temp is wrong in the Home app

### ISSUE THREAD

**Issue by darwiniandude** [nitaybz/homebridge-sensibo-ac#64]
For the last few months at least, current temp is wrong in the home app. It's always 16 degrees, but I have seen 16.5. The sensibo app itself says 18.9 currently. Any ideas? Latest plugin version. Otherwise it works perfectly.

**Comment by benwebbbenwebb** [comment]
Hi @darwiniandude 
Are you still seeing this issue with the most recent releases?

If not I'll close this off as a stale issue soon.

**Comment by darwiniandude** [comment]
Thanks for the follow up! Yes this got resolved some time ago after one of the updates it seems, my apologies for not closing it off myself. Thanks for all the great work :)
