### ISSUE TITLE
Password with an &

### ISSUE THREAD

**Issue by mipaso** [nitaybz/homebridge-sensibo-ac#66]
Hi there

fyi if the character & is used in a password, then password check fails with error 401. 

You may want to insure and sanityse variable entries when parsing the config file.

**Comment by benwebbbenwebb** [comment]
Hi @mipaso 

I've just pushed an alpha release, [2.4.0-alpha.1](https://www.npmjs.com/package/homebridge-sensibo-ac/v/2.4.0-alpha.1), that should fix this issue

**Comment by mipaso** [comment]
hi @benwebbbenwebb 

sorry I overlook your answer !

it works perfectly. 

Thanks

**Comment by mipaso** [comment]
corrected

**Comment by benwebbbenwebb** [comment]
Thanks for the feedback @mipaso 

I'll make sure the fix is included in the next main release
