### ISSUE TITLE
Auto OFF after temperature below target

### ISSUE THREAD

**Issue by 350d** [nitaybz/homebridge-sensibo-ac#67]
Hello!

I have AC unit with external temperature sensor and thermostat. So, if I disable my thermostat (just turn it off) - I still can control my AC with remote but it will not turn off/on automatically based on temperature settings I made via remote control.

Since SENSIBO is not thermostat - is this possible to add this option to config to auto OFF after target temperature is reached and ON after its go higher?
Two new config parameters needed, first - to enable this feature, second - delta, +-1º for example, when ON/OFF command should be fired.

Is that make sense or crazy idea?

**Comment by nitaybz** [comment]
Fir that, you have the Climate area ready feature, in the Sensibo app. Then, you can turn this feature on/off via HomeKit.

Another possibility is to create automations based on the room temperature via 3rd party apps like Eve or Home+.

Hope that helps...

**Comment by 350d** [comment]
In climate React I need to select exact temperature and this is a problem, because its should be my target temperature.

**Comment by nitaybz** [comment]
Climate React would allow you to set the AC in a certain ON state when crossing a certain temperature and turn it OFF when crossing another line. For example:
Set the AC to COOL 24, High Fan when temperature rises above 26 degrees.
+ set the AC to off when Temp is below 22.

This will give you a thermostat like feature with a given threshold.

**Comment by 350d** [comment]
Correct, but this is a hardcoded preset for single specific temperature, not for dynamically changed target temperature I can set via HomeKit UI on in Sensibo app itself.

**Comment by 350d** [comment]
Well, I've decided to go forward with TADO, they have thermostat mode on their units.
