### ISSUE TITLE
Sensibo via Hoobs

### ISSUE THREAD

**Issue by fabiovit** [nitaybz/homebridge-sensibo-ac#68]
Hello!
Is it normal for homebridge to lose the device cache at each reboot (either homebridge or sensibo), thus canceling any given name and created scenes?
Thanks

**Comment by nitaybz** [comment]
No it's not normal

**Comment by fabiovit** [comment]
I solved it by carrying out the manual configuration (using advantage) and not the basic one proposed by hoobs.
