### ISSUE TITLE
Sensibo Pure still show on homekit with ignoreHomeKitDevices set to true

### ISSUE THREAD

**Issue by Niklas31** [nitaybz/homebridge-sensibo-ac#69]
I recently bought a Sensibo Pure and configured it to work with HomeKit via official support.
I also have Sensibo Sky in my home set up and the only device I want to control over Hoobs is Sky.
For that, I set the `ignoreHomeKitDevices: true` so it would not duplicate.

Yet the device still shows on Home App duplicated (Oficial and Hoobs). The only difference is that now the Pure from Hoobs does not respond to commands. Is this the expected behavior? 

![image](https://user-images.githubusercontent.com/64484669/129615257-08933f39-1e19-4059-a68f-2e6eb04e82de.png)

**Comment by benwebbbenwebb** [comment]
Hi @Niklas31 

I don't have a Pure to try this with, but when I tested with my Air Plus (Airq) the device was removed from both Homebridge and the Apple Home app
