### ISSUE TITLE
Wrong device shown in Accessories Tab (Homebridge UI) 

### ISSUE THREAD

**Issue by luissimoes** [nitaybz/homebridge-sensibo-ac#70]
I switched 2 Sensibo devices (Office <-> Bedroom)
I updated the Location in the Sensibo App... and it works as it would i.e. the new Office device controls the Office AC and the new Bedroom device controls the Bedroom AC

In the Home App (shown though Homebridge) each device also controls the correct AC
BUT in the Accessories Tab in Homebridge Web the control is still "switched" i.e.
The Bedroom device controls the "Office" and vice-versa... i.e. the changes in the Sensibo App and in the Sensibo server somehow are not reflected in the Accessories (although the home app has it right)

**Comment by benwebbbenwebb** [comment]
Hi @luissimoes 
I believe that this is the same as #71 ...

An accessory is assigned once in Homebridge and won'y automatically move, you will need to manually correct this
