### ISSUE TITLE
Wrong Room name read (room doesn't exist anymore)

### ISSUE THREAD

**Issue by luissimoes** [nitaybz/homebridge-sensibo-ac#71]
(May be this is connected the potential issue I opened earlier - sorry to repeat if it is...)

The accessories tab reports a device in a non-existing room...
Here is an example 
- Room was "Sleeping Room" in the Sensibo App.
- I changed it to Bedroom
- it still shows "Sleeping Room" in the Accessories although the room doesn't exist in Sensibo

**Comment by benwebbbenwebb** [comment]
Hi @luissimoes 
As I understand it, once a room is created in Homebridge and an accessory is assigned to it, the accessory won't automatically be moved if you change the room name in a separate app (e.g. Sensibo).

I think you need to change the name of the room in Homebridge manually now.
