### ISSUE TITLE
Allow to select fan mode

### ISSUE THREAD

**Issue by bcyng** [nitaybz/homebridge-sensibo-ac#74]
currently fan mode is implemented as a separate accessory which allows to control fan speed. have to set the mode to OFF in the main accessory and then adjust the fan speed in the fan accessory.

would be good to make one of the modes fan mode in the main accessory - so its Auto/Heat/Cool/Fan/Off
currently need to go into the sensibo app to change the mode to fan mode.

can probably do the same with dry mode.

**Comment by benwebbbenwebb** [comment]
This looks to be a limitation of the Apple HomeKit APIs (and then brought through to Homebridge APIs).

'Valid' modes for an AC (in HomeKit) are:
INACTIVE
IDLE
HEATING
COOLING

**Comment by benwebbbenwebb** [comment]
Can't add to plugin / won't fix due to limitations of Apple HomeKit / Homebridge
