### ISSUE TITLE
Missing features - vertical swing and night mode

### ISSUE THREAD

**Issue by alloploid** [nitaybz/homebridge-sensibo-ac#75]
Hi,

Great job with the plugin. It works really nice. 
I miss very much two functionalities needed for AC "night mode".

1. Vertical swing - it's hard to sleep when AC blows right at you
2. SIlence mode - you know, it's easier to sleep in silence 

Do you have them in your plans?

**Comment by nitaybz** [comment]
Both of them exist in the plugin.
Vertical Swing is available in the accessory setting and it written as "Oscillate" and silence mode is just the lowest fan speed

**Comment by alloploid** [comment]
I cannot see "Oscillate". Also if I set fan speed, AC is turning off and fan mode is activating. 
In Sensibo app all options are supported and working. It's LG Artcool. 

Is possible to override the auto-configuration

![IMG_0998](https://user-images.githubusercontent.com/91637681/148703233-7b501737-ec7d-40d2-9f21-923feb32d023.PNG)
![IMG_0997](https://user-images.githubusercontent.com/91637681/148703237-ab11ad34-866f-45a7-b0b1-b49e0c82992d.jpg)
?

**Comment by nitaybz** [comment]
Click on the AC accessory, and scroll down to its settings, you'll see what I'm talking about.
You can also click "show as separate tiles" to split the tiles. I also suggest you to read the README so you can understand the plugin better

**Comment by kp9928** [comment]
My sensibo have vertical and horizontal swing, but just like this guy here - I too do not have "oscillate". 
A second question I have is about that "Fan" accessory which I too have - which seems to do nothing. What is that for?

**Comment by benwebbbenwebb** [comment]
Stale issue without much detail

If you still have problems please open a new issue and include your Sensibo API response by running the plugin in debug mode.
