### ISSUE TITLE
Use motion sensor in homekit

### ISSUE THREAD

**Issue by tkilik11** [nitaybz/homebridge-sensibo-ac#81]
Is it possible to use the sensibo motion sensor in homekit?

**Comment by benwebbbenwebb** [comment]
Hi @tkilik11 

I don't have any Sensibo Motion Sensors to try, but looking at the code from @nitaybz originally they should already be supported by the plugin

**Comment by benwebbbenwebb** [comment]
Closing as should already be delivered

Please @ me @tkilik11 if you are still having issues.
