### ISSUE TITLE
Using Homepod Mini

### ISSUE THREAD

**Issue by azarior619** [nitaybz/homebridge-sensibo-ac#83]
Since the last iOS update (15.4.1) Siri can't manage the ACs connected with Sensibo.
When I ask her to turn on the AC she asks me for the specific AC instead of turning on the one located in the same room with her.
Also, whenever I'm asking her to turn off the AC she turns it on instead, even when I'm asking her to "shut down the AC".

All worked fine with the previous version.

**Comment by nfxhk** [comment]
I have the same issue. Also can’t change the temperature. Weirdly, turning on the AC works just fine

**Comment by tatooye** [comment]
I have the same issue I can't turn off the AC with Siri but work fine to turn on the ac

**Comment by azarior619** [comment]
Solved on iOS 15.5
