### ISSUE TITLE
Doesn't support product model airq

### ISSUE THREAD

**Issue by oskarstucki** [nitaybz/homebridge-sensibo-ac#84]
I think the issues is in file syncHomeKitCache.js where there is no support for 
"productModel":"airq"

Example response from homebridge terminal from sensibo-api:

`[{"id":"fbgGqitf","temperatureUnit":"C","room":{"uid":"MroCTQ4a","name":"olohuone","icon":"Livingroom"},"acState":{"timestamp":{"time":"2022-06-10T20:05:21.186848Z","secondsAgo":0},"on":false,"mode":"auto","targetTemperature":22,"temperatureUnit":"C","fanLevel":"low","swing":"stopped"},"location":{"occupancy":"n/a","name":"Default Home","id":"iAwGYUGrqw"},"productModel":"airq","serial":"XXXXXX","motionSensors":[],"filtersCleaning":{"acOnSecondsSinceLastFiltersClean":13906,"filtersCleanSecondsThreshold":1080000,"lastFiltersCleanTime":null,"shouldCleanFilters":false},"pureBoostConfig":null,"homekitSupported":true,"remoteCapabilities":{"modes":{"cool":{"temperatures":{"F":{"isNative":false,"values":[63,64,66,68,70,72,73,75,77,79,81,82,84,86]},"C":{"isNative":true,"values":[17,18,19,20,21,22,23,24,25,26,27,28,29,30]}},"fanLevels":["low","medium_low","medium","medium_high","high","auto","strong"],"swing":["stopped","rangeFull"]},"heat":{"temperatures":{"F":{"isNative":false,"values":[46,63,64,66,68,70,72,73,75,77,79,81,82,84,86]},"C":{"isNative":true,"values":[8,17,18,19,20,21,22,23,24,25,26,27,28,29,30]}},"fanLevels":["low","medium_low","medium","medium_high","high","auto","strong"],"swing":["stopped","rangeFull"]},"fan":{"temperatures":{},"fanLevels":["low","medium_low","medium","medium_high","high","auto","strong"],"swing":["stopped","rangeFull"]},"auto":{"temperatures":{"F":{"isNative":false,"values":[63,64,66,68,70,72,73,75,77,79,81,82,84,86]},"C":{"isNative":true,"values":[17,18,19,20,21,22,23,24,25,26,27,28,29,30]}},"fanLevels":["low","medium_low","medium","medium_high","high","auto","strong"],"swing":["stopped","rangeFull"]},"dry":{"temperatures":{"F":{"isNative":false,"values":[63,64,66,68,70,72,73,75,77,79,81,82,84,86]},"C":{"isNative":true,"values":[17,18,19,20,21,22,23,24,25,26,27,28,29,30]}},"fanLevels":["low"],"swing":["stopped","rangeFull"]}}},"smartMode":{"enabled":true,"type":"humidity","deviceUid":"zXXXXX","lowTemperatureThreshold":null,"highTemperatureThreshold":48,"lowTemperatureState":null,"highTemperatureState":{"on":true,"targetTemperature":22,"temperatureUnit":"C","mode":"dry","fanLevel":"low","swing":"stopped"},"lowTemperatureWebhook":null,"highTemperatureWebhook":null},"measurements":{"time":{"time":"2022-06-10T20:04:05.625111Z","secondsAgo":75},"temperature":25.1,"humidity":68.2,"feelsLike":25.1,"rssi":0,"motion":false,"roomIsOccupied":null,"tvoc":7,"co2":405}}]`

**Comment by Flip76** [comment]
Would be nice to add airq too (same as sky but additionally tvoc und co2)

**Comment by benwebbbenwebb** [comment]
See also #72

**Comment by benwebbbenwebb** [comment]
For those looking for a fix, I have submitted a PR, #94, for this issue.

As a workaround (until it is merged) please see my alternate NPM package https://www.npmjs.com/package/@benwebbbenwebb/homebridge-sensibo-ac

**Comment by benwebbbenwebb** [comment]
Release v2.3.1 adds support for these devices

**Comment by oskarstucki** [comment]
Great! Thanks @benwebbbenwebb
