### ISSUE TITLE
Fan mode and Dry mode ?

### ISSUE THREAD

**Issue by Pblondin123** [nitaybz/homebridge-sensibo-ac#88]
Hi!  good job on the plugin.   Am sure this was discussed before:   is it possible to have the Fan and Dry modes as part of the accessory modes in Homekit, instead of going thru separate accessories ?  The mapping experience between HK and Sensibo would be better.  Thanks!

**Comment by Pblondin123** [comment]
realizing is same as issue #74 :-)

**Comment by benwebbbenwebb** [comment]
Closing as duplicate of #74
