### ISSUE TITLE
Feature Request: Option to disable vertical swing

### ISSUE THREAD

**Issue by RB72** [nitaybz/homebridge-sensibo-ac#90]
I am using two Sensibo Air’s to control airco’s with HomeKit.
Would it be possible to add a config option (disableVerticalSwing?) to disable the vertical swing button?
Thank you in advance!

**Comment by RB72** [comment]
Is it possible to implement this option?

**Comment by benwebbbenwebb** [comment]
Sure @RB72, I’ll take a look

Double checking, is the goal to hide the Oscillate (vertical swing) switch/sliders when looking at the Accessories in Homebridge and Apple Home app?

**Comment by RB72** [comment]
Correct.
I don’t want users to change the horizontal and vertical swing. The horizontal swing is already configurable to be disabled, but the vertical swing is not. In the Home app the AC accessoire has a button to turn on/off the (vertical) swing. I would like to disable/hide that button if possible. 
Thanks in advance!
![26B32289-E384-42EC-B305-B5E80146D03C](https://user-images.githubusercontent.com/82523064/209476811-03ba6990-dfc3-4e77-904f-acf236f53e68.jpeg)

**Comment by benwebbbenwebb** [comment]
Hi @RB72 

I've just pushed an alpha release, [2.4.0-alpha.1](https://www.npmjs.com/package/homebridge-sensibo-ac/v/2.4.0-alpha.1), that includes this enhancement.

New option added, disableVerticalSwing.

One thing I did note is that for this change to take effect in the Home app you'll unfortunately need to "reset" the Aircon accessory by using the in-built Homebridge 'Remove Single Cached Accessory' option within Homebridge Settings.

I'll take a look over the next few days to see if it's possible to change that requirement.

**Comment by RB72** [comment]
Hi Ben,
Yeah, great, that is exactly what I needed, thank you 🙏 👍
Indeed it would be better if one doesn’t need to clear the cached devices, so hopefully you can find something for that too.
Kind regards,
René

**Comment by benwebbbenwebb** [comment]
Hey René  @RB72 

Is it possible for you to share the swing / verticalSwing section(s) of your Sensibo response payload?

Examples:
"swing": [
	"stopped",
	"rangeFull"
]


"swing": [
	"stopped",
	"rangeFull",
	"horizontal",
	"both"
]

**Comment by RB72** [comment]
Sure;

"swing":["stopped","fixedTop","fixedMiddleTop","fixedMiddle","fixedMiddleBottom","fixedBottom","rangeFull"],"horizontalSwing":["stopped","fixedLeft","fixedCenterLeft","fixedCenter","fixedCenterRight","fixedRight","fixedLeftRight","rangeCenter","rangeFull"]

**Comment by benwebbbenwebb** [comment]
Hi @RB72 

I've spent some more time on this and haven't found a solution to 'force' a refresh back to the Home app unfortunately.

I've raised an [issue / question](https://github.com/homebridge/homebridge/issues/3299) with the core Homebridge platform asking for assistance so will see what they suggest if and when they come back.

For now the work-around of removing and re-adding the accessory will have to do when a user wants to remove a cached characteristic.

**Comment by RB72** [comment]
Yes, that is not a problem. Perhaps a little footnote in user interface or something like that to get the users attention when you change this setting you have to remove the single cached device. This perhaps prevents some support questions 😁
