### ISSUE TITLE
How to ignore the Current Temperature and Humidity 

### ISSUE THREAD

**Issue by Sigalov** [nitaybz/homebridge-sensibo-ac#92]
Hi,
How to ignore "Current Temperature and Humidity", I don't want to see it in the Home (iOS) app?
I have another sensor that I use.

**Comment by benwebbbenwebb** [comment]
Hi @Sigalov 

While it would definitely be possible to remove / suppress the Current Humidity from the AC entry, it won't be possible to remove Current Temperature as that is a required field on the HeaterCooler service type (I also checked other types such as thermostat).

**Comment by benwebbbenwebb** [comment]
Closing as we can't remove Current Temperature

Keep an eye out for future releases where we may include an option to disable display of Current Humidity.
