### ISSUE TITLE
Problem with version 2.3.1 and 2.3.3

### ISSUE THREAD

**Issue by RB72** [nitaybz/homebridge-sensibo-ac#97]
I have two Sensibo Air modules, they were working fine with plugin 2.2.0.
After updating to version 2.3.1 or version 2.3.3 they are gone in Apple Home.
Homebridge (v1.6.0) does not show any error messages, also after enabling debug logging for the plugin there are no errors or warnings.
I reverted to plugin version 2.2.0 to get the modules working again.

**Comment by RB72** [comment]
My config:
            "apiKey": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "disableFan": true,
            "disableDry": true,
            "ignoreHomeKitDevices": false,
            "enableSyncButton": false,
            "syncButtonInAccessory": false,
            "enableOccupancySensor": false,
            "enableClimateReactSwitch": false,
            "enableHistoryStorage": false,
            "disableHorizontalSwing": true,
            "disableLightSwitch": true,
            "externalHumiditySensor": false,
            "allowRepeatedCommands": false,
            "debug": false,
            "_bridge": {
                "username": "XX:XX:XX:XX:XX:XX",
                "port": 36924
            },
            "platform": "SensiboAC"

**Comment by ddong3000** [comment]
Me too. Where is my Sensibo?

**Comment by ddong3000** [comment]
> Me too. Where is my Sensibo?

Solved it myself
If you entered ID and password, do not enter API

**Comment by njuart** [comment]
Same problem for me, my AC units disappeared after update, but I still see humidity sensors. I'm logged in with creds, without API key.

**Comment by slawnz** [comment]
Same issue for me. Logged in via API, cred fields empty. Been working great until update. Only have humidity sensors with latest version. Reverted to 2.2.0 and AC units came back. Please fix!

**Comment by hardlock75** [comment]
same situation... rollback on 2.2.0 working great

**Comment by orianlevy** [comment]
Same here, AC is gone from HomeKit

**Comment by mao832** [comment]
Confirmed same issue also for me, reverted to 2.2.0 version and everything again is back as normal.

**Comment by jsalva23** [comment]
same happened to me, how do I revert back to 2.2.0? also will I loose all my automations that include sensibo accessories?

**Comment by jsalva23** [comment]
hey guys any updates here?

**Comment by RB72** [comment]
To revert (if you are using Homebridge) go to the tab Plugins and click on the wrench of the Sensibo plugin, then choose Install Previous Version.

**Comment by shivanathd** [comment]
I reverted back to 2.2 and can confirm all the automations, scenes and button associates all got nuked and have to start from scratch for those ACs

**Comment by JacVid** [comment]
I confirm, at home, same issue with version 2.3.x. I switched back to 2.2.0 to retrieve my devices.

**Comment by shivanathd** [comment]
@JacVid did it remove it from your automations and scenes?

**Comment by JacVid** [comment]
yes, the devices had completely disappeared from my home.

**Comment by shivanathd** [comment]
yeah .. i think we ahve to live with it

**Comment by gorlar954** [comment]
Instämmer med ovanstående, funkar bara med 2.2

**Comment by shivanathd** [comment]
@nitaybz

**Comment by rmeredit** [comment]
My setup also has stopped working with versions 2.3.1 and 2.3.3.  Humidity and temperature sensors reporting fine, but climate react switch ineffective.  Tried alternatively using username and password or the API key and neither had any effect.

Reverting to 2.2.0 restored functionality.

Here's my config, running on Homebridge 1.6.0:

{
    "apiKey": "[removed]",
    "disableFan": false,
    "disableDry": false,
    "ignoreHomeKitDevices": false,
    "enableSyncButton": false,
    "syncButtonInAccessory": false,
    "enableOccupancySensor": false,
    "enableClimateReactSwitch": true,
    "enableHistoryStorage": false,
    "disableHorizontalSwing": false,
    "disableLightSwitch": true,
    "externalHumiditySensor": true,
    "allowRepeatedCommands": false,
    "debug": false,
    "platform": "SensiboAC"
}

**Comment by minuscorp** [comment]
Not working here also, using 2.2.0 to make it work

**Comment by benwebbbenwebb** [comment]
Hi all / @RB72 

Very sorry to hear about the issue!

Would it be possible to please turn on debug mode ("debug": true in the config) and provide an anonymised version of the Sensibo API response?

Right now I'm specifically interested in what's stated for "productModel", but the full response will be most useful moving forward.

Would also be great to get a copy of any Sensibo plugin specific error or warning messages when Homebridge restarts.

**Comment by RB72** [comment]
“productModel”:”skyplus”
There are no errors…

**Comment by benwebbbenwebb** [comment]
Thanks @RB72 

I've just created a beta version of v2.3.4 and released it on NPM which includes a hotfix

In Homebridge you'll need to select it from the 'Alternate Versions' menu.

**Comment by RB72** [comment]
Yeah, that seems to fix it.
I upgraded to 2.3.4 beta and my units are still there 👍
Thank you very much and merry Christmas!

**Comment by njuart** [comment]
Just installed beta, and devices disappeared again...

“productModel”:”skyv2”

**Comment by benwebbbenwebb** [comment]
Thanks for the update @RB72

Sorry for the continued trouble @njuart 

I've update the logic to be more generic for both Sky and Air devices, hopefully this resolves it!

Please try 2.3.4-beta2

**Comment by RB72** [comment]
For me 2.3.4 beta2 is still working fine.

**Comment by njuart** [comment]
Thx, a lot 🤝 Works fine now

**Comment by benwebbbenwebb** [comment]
v2.3.4-release version now available and should resolve the issue of (some) Sky devices not showing correctly

Thanks to @RB72 and @njuart for the testing help

**Comment by rmeredit** [comment]
2.3.4 confirmed working for Sensibo Air as well.  Thanks for the fix!

**Comment by slawnz** [comment]
@benwebbbenwebb I've upgraded to 2.3.4 and two of my three skyv2 are working, one shows up in HomeKit as "This accessory is not currently supported by the Home app" -- was fine on 2.2

**Comment by benwebbbenwebb** [comment]
> @benwebbbenwebb I've upgraded to 2.3.4 and two of my three skyv2 are working, one shows up in HomeKit as "This accessory is not currently supported by the Home app" -- was fine on 2.2

That sounds a bit odd @slawnz 

Any chance you can share your Sensibo API response and other debug log info? It will be in the Homebridge logs when you turn on Debug mode within the homebridge-sensibo-ac plugin config.

**Comment by nitaybz** [comment]
@slawnz this is something that was always there.... accessories that are not official (coming from Homebridge) will always show this message

**Comment by slawnz** [comment]
@benwebbbenwebb Deleting the bridge from my home and re-adding it fixed the problem

**Comment by mao832** [comment]
2.3.4 fixed the issue also for me, thanks for the support and Merry Christmas to all!

**Comment by benwebbbenwebb** [comment]
Closing as, based on feedback, resolved with v2.3.4
