### ISSUE TITLE
Eve history stopped working

### ISSUE THREAD

**Issue by joussen** [nitaybz/homebridge-sensibo-ac#99]
Hi, the Eve history feature stopped working about a month ago. The Eve app shows the current temperature, but no history. I enabled the debug log, but it doesn't show anything suspicious. I wonder what changed. Any ideas how to track down what's going wrong are appreciated.

**Comment by joussen** [comment]
I am not sure what changed. But the history started working again. I close this issue.

**Comment by joussen** [comment]
Unfortunately the history stopped working again. So, I reopen this issue.
Any ideas on how to debug the problem are appreciated.

**Comment by benwebbbenwebb** [comment]
Hi @joussen 

Unfortuantely I'm not familiar with the History feature as it was implemented before I joined the project and I, generally, don't use the Eve app.

That said, I have just released a new alpha version of this plugin that includes version bumps of the dependencies, including the one used for history, fakegato-history.

Do you want to give that a try?

**Comment by ovq** [comment]
@benwebbbenwebb it seems there was never any feedback on this from the OP. To close the issue, let me report that the alpha fully restores history in Eve. Nice!
